name: Build and Push Docker Images on Push

on:
  push:
    branches:
      - main

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      desktop: ${{ steps.check.outputs.desktop }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: check files changes at the path
      id: check
      run: |
        desktop_img_changed=$(git diff --name-only HEAD~1 | grep '^docker/desktop' || true)
        echo "desktop=$([ -n "$desktop_img_changed" ] && echo 'yes' || echo 'false')" >> $GITHUB_ENV
        echo $desktop_img_changed
        echo $desktop

  build-and-push:
    name: build and push 
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.desktop == 'yes'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    # - name: Login to Docker Hub
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    #     DOCKER_PWD: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
    #   run: |
    #     docker login -u $DOCKER_USER -p $DOCKER_PWD

    - name: Build and push desktop
      run: |
        echo "Running"
    