name: Build and publish images on every new release

on:
  release:
    type: [created]

jobs:
  build_and_push:
    name: Build and push the docker images to container registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker 
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}"" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Get the release tag
      run: | 
        echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
    
    - name: Build the image
      run: docker build . --tag mohanj7/${{ env.REPO_NAME }}:${{ env.TAG }}
    
    - name: Push the image
      run: |
        docker tag mohanj7/${{ env.REPO_NAME }}:${{ env.TAG }} mohanj7/${{ env.REPO_NAME  }}:latest
        docker push mohanj7/${{ env.REPO_NAME }}:${{ env.TAG }}
        docker push mohanj7/${{ env.REPO_NAME  }}:latest

